### ISSUE TITLE
Need Contact details

### ISSUE THREAD

**Issue by nk-gears** [HarshJivani08/FakePostGenerator#1]
Hi Harsh,

I came across your profile in Linked In and would like to talk to you for a new Project for our NGO. Will you be available to work with us in the weekends part time?

Please reach out me in twitter.com/nirmal_kumar

**Comment by HarshJivani08** [comment]
Hi , Please Can you send your email or Contact number.

**Comment by HarshJivani08** [comment]
> Hi Harsh,
> 
> I came across your profile in Linked In and would like to talk to you for a new Project for our NGO. Will you be available to work with us in the weekends part time?
> 
> Please reach out me in twitter.com/nirmal_kumar


Hi , 
Nirmal kumar,
Please ! Can you send your email or Contact number ?

**Comment by nk-gears** [comment]
> > Hi Harsh,
> > 
> > I came across your profile in Linked In and would like to talk to you for a new Project for our NGO. Will you be available to work with us in the weekends part time?
> > 
> > Please reach out me in twitter.com/nirmal_kumar
> 
> 
> Hi , 
> Nirmal kumar,
> Please ! Can you send your email or Contact number ?
> 
> 

Message me in whatsapp : 9283 ---- xxxxxx
